- name: Ensure appimage directory exists
  ansible.builtin.file:
    path: '{{ appimage_dir }}'
    state: directory
    mode: '0700'

# appimages needs fuse2 to run
- name: Install fuse2
  become: true
  ansible.builtin.dnf:
    name: [fuse, fuse-libs]
    state: present
  when: settings.appimages | length > 0

- name: Download appimage (github)
  github-release-download:
    project: '{{ item.github }}'
    tag: '{{ item.version | default("") }}'
    match_asset: '{{ item.match_asset | default("^.*\.AppImage$") }}'
    dest: '{{ appimage_dir }}/{{ item.name }}.AppImage'
    mode: '0700'
  loop: '{{ settings.appimages }}'

- name: Ensure desktop icon directory exists
  ansible.builtin.file:
    path: '{{ appimage_dir }}/icon'
    state: directory
    mode: '0700'

- name: Check if desktop icon already exist
  ansible.builtin.stat:
    path: '{{ appimage_dir }}/icon/{{ item.name }}.{{ (item.icon | basename | split("."))[-1] }}'
  when: item.icon is defined
  loop: '{{ settings.appimages }}'
  register: found_icons

- name: Download desktop icon
  ansible.builtin.get_url:
    url: '{{ item.item.icon }}'
    dest: '{{ appimage_dir }}/icon/{{ item.item.name }}.{{ (item.item.icon | basename | split("."))[-1] }}'
    mode: '0600'
  loop: '{{ found_icons.results | selectattr("stat.exists", "==", false) }}'

- name: Create desktop entry
  ansible.builtin.template:
    src: appimage.desktop.j2
    dest: ~/.local/share/applications/{{ item.name }}.desktop
    mode: '0600'
  loop: '{{ settings.appimages }}'
