- name: Disable mouse acceleration
  community.general.dconf:
    key: '/org/gnome/desktop/peripherals/mouse/accel-profile'
    value: "'flat'"
    state: present

- name: Static workspaces
  community.general.dconf:
    key: '{{ item.key }}'
    value: '{{ item.value }}'
    state: present
  loop:
    - { key: '/org/gnome/mutter/dynamic-workspaces', value: 'false' }
    - { key: '/org/gnome/desktop/wm/preferences/num-workspaces', value: '4' }
    - { key: '/org/gnome/shell/app-switcher/current-workspace-only', value: 'true' }

- name: File manager single click
  community.general.dconf:
    key: '/org/gnome/nautilus/preferences/click-policy'
    value: "'single'"
    state: present

- name: Sort folders before files
  community.general.dconf:
    key: '{{ item }}'
    value: 'true'
    state: present
  loop:
    - '/org/gtk/settings/file-chooser/sort-directories-first'
    - '/org/gtk/gtk4/settings/file-chooser/sort-directories-first'

- name: Disable automatic updates
  community.general.dconf:
    key: '{{ item.key }}'
    value: '{{ item.value }}'
    state: present
  loop:
    - { key: '/org/gnome/software/allow-updates', value: 'false' }
    - { key: '/org/gnome/software/download-updates', value: 'false' }
    - { key: '/org/gnome/software/download-updates-notify', value: 'false' }

- name: Disable hot corner
  community.general.dconf:
    key: '/org/gnome/desktop/interface/enable-hot-corners'
    value: 'false'
    state: present

- name: Disable logout delay
  community.general.dconf:
    key: '/org/gnome/gnome-session/logout-prompt'
    value: 'false'
    state: present

- name: Disable edge tiling
  community.general.dconf:
    key: '/org/gnome/mutter/edge-tiling'
    value: 'false'
    state: present
