- name: Check syncthingtray version
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      REGEX="Syncthing Tray, version ([0-9]+\.[0-9]+\.[0-9]+)"
      [[ "$(syncthingtray -h)" =~ $REGEX ]] && echo "${BASH_REMATCH[1]}"
  changed_when: false
  ignore_errors: true
  register: syncthingtray_version

- name: Download syncthingtray
  github-release-download:
    project: Martchus/syncthingtray
    tag: 'v{{ versions.syncthingtray }}'
    match_asset: '^syncthingtray-.*-x86_64-pc-linux-gnu.tar.xz$'
    dest: /tmp
  when: syncthingtray_version.failed or syncthingtray_version.stdout != versions.syncthingtray
  register: syncthingtray_download

- name: Unarchive syncthingtray
  ansible.builtin.unarchive:
    src: '{{ syncthingtray_download.dest }}'
    dest: /tmp
    list_files: true
  when: not syncthingtray_download is skipped
  register: syncthingtray_unarchive

- name: Install syncthingtray
  become: true
  ansible.builtin.copy:
    src: /tmp/syncthingtray
    dest: /usr/local/bin/syncthingtray
    owner: root
    group: root
    mode: '0755'
  when: not syncthingtray_download is skipped
